openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 1.0.0
servers:
  - url: "{server}:{port}/"
    variables:
      server:
        default: http://localhost
      port:
        default: "9090"
paths:
  /accounts:
    get:
      summary: Get all accounts data
      operationId: getUsers
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/account"
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    account:
      required:
        - account_id
        - age
      type: object
      properties:
        account_id:
          type: string
        balances:
          $ref: "#/components/schemas/balances"
        mask:
          type: string
        name:
          type: string
        official_name:
          type: string
        persistent_account_id:
          type: string
        subtype:
          type: string
        type:
          type: string

    balances:
      type: object
      properties:
        available:
          type: integer
        current:
          type: integer
        iso_currency_code:
          type: string
        limit:
          type: integer
        unofficial_currency_code:
          type: string
