openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 1.0.0
servers:
  - url: "{server}:{port}/"
    variables:
      server:
        default: http://localhost
      port:
        default: "9090"
paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Users:
      required:
        - name
        - age
      type: object
      properties:
        name:
          type: string
        age:
          type: string
